-- IF YOU UPDATE THIS FILE, DON'T FORGET TO INCREMENT THE Schema.VERSION!
-- This are basic tables that must be created prior
-- to creation of tables containing elements.

CREATE TABLE IF NOT EXISTS RESOURCE(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	RESOURCEPATH VARCHAR NOT NULL,
	TYPE VARCHAR NOT NULL,
	PREFIX VARCHAR NOT NULL,
	PATH VARCHAR NOT NULL
);