-- IF YOU UPDATE THIS FILE, DON'T FORGET TO INCREMENT THE Schema.VERSION!
-- This are basic tables that must be created prior
-- to creation of tables containing elements.

CREATE TABLE IF NOT EXISTS ROUTES(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ACTION VARCHAR NOT NULL,
	NAME VARCHAR NOT NULL,
	PATTERN VARCHAR NOT NULL,
	CONTROLLER VARCHAR NOT NULL,
	BUNDLE VARCHAR NOT NULL,
	PATH VARCHAR NOT NULL
);