-- IF YOU UPDATE THIS FILE, DON'T FORGET TO INCREMENT THE Schema.VERSION!
-- This are basic tables that must be created prior
-- to creation of tables containing elements.

CREATE TABLE IF NOT EXISTS ROUTES(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ACTION VARCHAR,
	NAME VARCHAR NOT NULL,
	PATTERN VARCHAR,
	CONTROLLER VARCHAR NOT NULL,
	BUNDLE VARCHAR NOT NULL,
	PATH VARCHAR NOT NULL
);
CREATE INDEX R_ACTION_IDX ON ROUTES(ACTION);
CREATE INDEX R_NAME_IDX ON ROUTES(NAME);
CREATE INDEX R_BUNDLE_IDX ON ROUTES(BUNDLE);
CREATE INDEX R_CONTROLLER_IDX ON ROUTES(CONTROLLER);
CREATE INDEX R_PATH_IDX ON ROUTES(PATH);
