-- IF YOU UPDATE THIS FILE, DON'T FORGET TO INCREMENT THE Schema.VERSION!
-- This is a table for element declarations. Table name
-- is substituted in a runtime.

CREATE TABLE IF NOT EXISTS {0}(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	PATH VARCHAR NOT NULL UNIQUE,
	NAME VARCHAR NOT NULL UNIQUE,
	PHPCLASS VARCHAR NOT NULL,
	TIMESTAMP BIGINT NOT NULL
	
);